export const GET_All_CONTEST_REQUEST = 'GET_All_CONTEST_REQUEST'
export const GET_All_CONTEST_SUCCESS = 'GET_All_CONTEST_SUCCESS'
export const GET_All_CONTEST_FAIL = 'GET_All_CONTEST_FAIL'

export const GET_SINGLE_CONTEST_REQUEST = 'GET_SINGLE_CONTEST_REQUEST'
export const GET_SINGLE_CONTEST_SUCCESS = 'GET_SINGLE_CONTEST_SUCCESS'
export const GET_SINGLE_CONTEST_FAIL = 'GET_SINGLE_CONTEST_FAIL'

// export const GET_All_CONTEST_REQUEST = 'GET_All_CONTEST_REQUEST'
// export const GET_All_CONTEST_SUCCESS = 'GET_All_CONTEST_SUCCESS'
// export const GET_All_CONTEST_FAIL = 'GET_All_CONTEST_FAIL'